### ISSUE TITLE
Example: Skycoin CLI in language X

### ISSUE THREAD

**Issue by olemis** [simelo/skycoin-libs-examples#3]
**Example summary**
Skycoin command line interface in language X

**Rationale**
Command line interface is an important entry point to all things Skycoin . Consider this as a proof of concept to know how to implement each command in the programming language of your preference , and maybe as a starting point to implement your own sophisticated tool .

**Languages and frameworks**

- [ ] C
- [ ] C#
- [ ] Java (OkHttp)
- [ ] Javascript / Typescript (nodejs)
- [ ] Objective-C
- [ ] Python
- [ ] R
- [ ] Ruby
- [ ] Rust (rust, rust-server)
- [ ] Swift (4.x)

**Implementation steps**

- [ ] `addPrivateKey`        Add a private key to specific wallet
- [ ] `addressBalance`       Check the balance of specific addresses
- [ ] `addressGen`           Generate skycoin or bitcoin addresses
- [ ] `addressOutputs`       Display outputs of specific addresses
- [ ] `addressTransactions`  Show detail for transaction associated with one or more specified addresses
- [ ] `addresscount`         Get the count of addresses with unspent outputs (coins).
- [ ] `blocks`               Lists the content of a single block or a range of blocks
- [ ] `broadcastTransaction` Broadcast a raw transaction to the network
- [ ] `checkDBDecoding`      Verify the database data encoding
- [ ] `checkdb`              Verify the database
- [ ] `createRawTransaction` Create a raw transaction to be broadcast to the network later
- [ ] `decodeRawTransaction` Decode raw transaction
- [ ] `decryptWallet`        Decrypt wallet
- [ ] `encryptWallet`        Encrypt wallet
- [ ] `fiberAddressGen`      Generate addresses and seeds for a new fiber coin
- [ ] `help`                 Help about any command
- [ ] `lastBlocks`           Displays the content of the most recently N generated blocks
- [ ] `listAddresses`        Lists all addresses in a given wallet
- [ ] `listWallets`          Lists all wallets stored in the wallet directory
- [ ] `pendingTransactions`  Get all unconfirmed transactions
- [ ] `richlist`             Get skycoin richlist
- [ ] `send`                 Send skycoin from a wallet or an address to a recipient address
- [ ] `showConfig`           Show cli configuration
- [ ] `showSeed`             Show wallet seed
- [ ] `status`               Check the status of current skycoin node
- [ ] `transaction`          Show detail info of specific transaction
- [ ] `verifyAddress`        Verify a skycoin address
- [ ] `verifyTransaction`    Verify if the specific transaction is spendable
- [ ] `version`              List the current version of Skycoin components
- [ ] `walletAddAddresses`   Generate additional addresses for a wallet
- [ ] `walletBalance`        Check the balance of a wallet
- [ ] `walletCreate`         Generate a new wallet
- [ ] `walletDir`            Displays wallet folder address
- [ ] `walletHistory`        Display the transaction history of specific wallet. Requires skycoin node rpc.
- [ ] `walletOutputs`        Display outputs of specific wallet
